apiVersion: batch/v1
kind: Job
metadata:
  name: agent
spec:
  template:
    spec:
      containers:
        - name: agent
          image: buildkite/agent:3
          args: ["start", "--disconnect-after-job"]
      restartPolicy: Never
